# Kubernetes Cert
cert:
  # 签发集群整数保存目录，默认签发10年有限期证书
  dir: /opt/certs
  # 签发证书大小
  size: 2048
  # 签发证书的时间
  day: 3650d

# Etcd
etcd:
  # etcd 版本
  version: 3.5.0
  # etcd 数据目录
  data_dir: "/var/lib/etcd"

# High Availability
# kube-apiserver负载均衡的信息
# 如使用haproxy + keepalived请填写VIP及端口
# 如使用公有云负载均衡请填写负载均衡IP及端口（需再安装之前自行配置）
# 如使用域名，需提前配置解析。不使用域名时，请注释掉
# 如使用haproxy + keepalived ，并且跟master节点部署在一起时，请修改port以避免端口冲突
loadbalance:
  ip: 172.16.90.100
  port: 6443
  #domain_name: apiserver.k8sre.com

# Kubernetes
kubernetes:
  # kubernetes 二进制安装包下载地址，默认为阿里云从Google同步过来的镜像，更新较慢，最新版本可能未同步过来。
  # 如使用自建文件服务器，请保证下载路径为:http://xxx.xxx.xxx/v1.21.2/bin/linux/amd64/kube-apiserver。
  download_url: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release
  # kubernetes 版本
  version: v1.22.1
  # 集群Pod网段
  podSubnet: 10.64.0.0/12
  # 集群Service网段
  serviceSubnet: 10.80.0.0/16
  # kubelet 数据目录
  kubelet_dir: "/var/lib/kubelet"
  # cni-plugins: https://github.com/containernetworking/plugins
  cni_plugins_version: v1.0.1

# Containerd
critools:
  version: v1.22.0
containerd:
  # containerd 版本,由yum list containerd.io --showduplicates | sort -r命令查询
  version: 1.4.9
  # containerd 持久化数据目录
  root: "/var/lib/containerd"
  # containerd 临时数据目录
  state: "/run/containerd"
  grpc:
    max_recv_message_size: 16777216
    max_send_message_size: 16777216
  debug:
    level: ""
  metrics:
    address: ""
    grpc_histogram: false
  cri:
    sandbox_image: "registry.aliyuncs.com/google_containers/pause:3.4.1"
    max_container_log_line_size: -1
  containerd:
    snapshotter: overlayfs
  options:
    SystemdCgroup: true
  registries:
    "docker.io": "https://registry-1.docker.io"
    "k8s.gcr.io": "https://registry.aliyuncs.com/k8sxio"

# Network Plugin
network_plugin: cilium
# cilium need linux kernel >= 4.9.17
cilium:
  version: v1.9.10
flannel:
  version: v0.14.0
  network_mode: vxlan
calico:
  version: v3.20.0
  network_mode: ipip

# Addons
coredns:
  version: 1.8.4
nodelocaldns:
  enabled: true
  version: 1.17.0
  ip: 169.254.20.10
metrics_server:
  enabled: true
  version: v0.5.0
helm:
  enabled: true
  version: v3.6.3
dashboard:
  enabled: true
  version: v2.3.1