---
containerd_root: "/var/lib/containerd"
containerd_state: "/run/containerd"
containerd_config:
  grpc:
    max_recv_message_size: 16777216
    max_send_message_size: 16777216
  debug:
    level: ""
  cri:
    sandbox_image: "registry.aliyuncs.com/google_containers/pause:3.3"
    max_container_log_line_size: -1
  containerd:
    snapshotter: overlayfs
  options:
    SystemdCgroup: "true"
  registries:
    "docker.io": "https://dockerhub.mirrors.nwafu.edu.cn"
    "k8s.gcr.io": "https://registry.aliyuncs.com/k8sxio"
