---
- name: Get cri-containerd-cni
  get_url:
    url: "https://ghproxy.com/https://github.com/containerd/containerd/releases/download/v{{ containerd.version }}/cri-containerd-cni-{{ containerd.version }}-linux-amd64.tar.gz"
    dest: /tmp/
    timeout: 60
  tags: install_containerd

- name: Install cri-containerd-cni
  unarchive:
    src: "/tmp/cri-containerd-cni-{{ containerd.version }}-linux-amd64.tar.gz"
    dest: /
    remote_src: yes
  tags: install_containerd
  notify:
    - Get crictl completion
    - Install crictl completion

- name: "Create containerd data directory"
  file:
    path: "{{ containerd.root }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: containerd_config

- name: "Create containerd config directory"
  file:
    path: "/etc/containerd"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: containerd_config

- name: "Set containerd config"
  template:
    src: "config.toml.j2"
    dest: "/etc/containerd/config.toml"
    owner: root
    group: root
    mode: 0644
  tags: containerd_config
  notify:
    - restart containerd

- name: "Config cri-tools"
  template:
    src: "crictl.yaml.j2"
    dest: "/etc/crictl.yaml"
    owner: root
    group: root
    mode: 0644
  tags: cri_tools
  